version: "3.9"
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "lexed"
      POSTGRES_USER: "lexed"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
